### ISSUE TITLE
Difference between WGAT and GraphAttention

### ISSUE THREAD

**Issue by yanistazi** [DeepRank/Deeprank-GNN#55]
Thank you for this amazing work very well documented !

Digging into the code , I noticed two modules very similar : GraphAttention and WGATConv.

Only difference is this line in WGATConv 
out = scatter_mean(alpha,col,dim=0,out=out)

It seems to be that the difference is related to directed vs undirected graphs.

Can you explain when to use one over the other and whether you have a reference to read for WGATConv?

Best,
Yanis

**Comment by manonreau** [comment]
Dear Yanis, 

This really depends on the system you are studying. Since deeprank-gnn considers residue-level data, it makes no sense to have a directed graph to represent the interactions.
