### ISSUE TITLE
antibodies and antigens

### ISSUE THREAD

**Issue by sunchuance** [DeepRank/Deeprank-GNN#73]
Hello, can this model predict the docking score of antibodies and antigens?

**Comment by manonreau** [comment]
Hello, 

the provided pre-trained model was not trained on such systems and requires PSSM information that you may not have for your antigens. If you have PSSM information, you can give it a try, if you don't I would advise training a new model without using the PSSM information. 

Please refer to the online documentation to learn how to train a model: 
https://deeprank-gnn.readthedocs.io/en/latest/index.html

++
Manon
