### ISSUE TITLE
Can't read output from example 1ATN

### ISSUE THREAD

**Issue by erikedlund** [DeepRank/Deeprank-GNN#74]
Thanks for creating such a cool resource and documenting it so thoroughly. I'm interested in using the pre-trained model from the publication on arbitrary inputs.

I've gone through the examples documented [here ](https://deeprank-gnn.readthedocs.io/en/latest/tutorial.train_model.html#use-deeprank-gnn-paper-s-pretrained-model)and successfully generated the .hdf5 outputs for 1ATN. However, when I go to use the converted in the tools directory to create a human-readable file, I get errors like this:

```
>>> hdf5_to_csv('./1ATN_residue.hdf5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dnas/git/Deeprank-GNN/deeprank_gnn/tools/hdf5_to_csv.py", line 14, in hdf5_to_csv
    mol = hdf5['{}/{}/mol'.format(epoch, dataset)]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/dnas/anaconda3/envs/deep-cpu/lib/python3.9/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'mol' doesn't exist)"
```

Is the converter out of sync with the results graphs generated?

**Comment by manonreau** [comment]
Dear Erike, 

Thanks for using DeepRank-GNN. I apologized, this hdf5_to_csv tool has been specifically designed to read the output of th graph neural network model, and not the input graphs that you provide it. In order to read the information contained in your hdf5 file you can type the following commands in python:

```
>>> import h5py
>>> F=h5py.File('1ATN_residue.hdf5')
>>> F.keys()
<KeysViewHDF5 ['1ATN_10w', '1ATN_1w', '1ATN_2w', '1ATN_3w', '1ATN_4w', '1ATN_5w', '1ATN_6w', '1ATN_7w', '1ATN_8w', '1ATN_9w']>
```
One graph has been generated for each system, you can then navigate through the graph information for each of them:
```
>>> F['1ATN_10w'].keys()
<KeysViewHDF5 ['clustering', 'edge_data', 'edge_index', 'edges', 'internal_edge_data', 'internal_edge_index', 'internal_edges', 'node_data', 'nodes', 'score']>
```
Fore example, if you want to have a look at the different nodes:
```
>>> F['1ATN_10w/nodes'][()]
array([[b'A', b'435', b'VAL'],
       [b'B', b'92', b'LEU'],
       [b'A', b'437', b'ARG'],
       [b'B', b'91', b'VAL'],... ])
```
You can also check out which information is hold by each node:
```
F['1ATN_10w/node_data'].keys()
F['1ATN_10w/node_data/pssm'][()]
```

We also developed a graphic tool to visualize the graphs contained in hdf5 files and navigate through their content:
You can use the following script:
`python ./Deeprank-GNN/deeprank_gnn/h5x/h5x.py
`
and click on the molecule files to access the content. You can also open a 3D plot of the molecule by clicking right on it and selecting 3D plot.

I hope this answer your question.

Best,

Manon

**Comment by erikedlund** [comment]
Thank you! I think I understand my mistake here. I'm able to go through the graph attributes as you described. I can also visualize the graphs with the viewer, which is a really cool feature.

My remaining question is how to access the predicted docking score values generated by the pre-trained model. Following along with the example "Use DeepRank-GNN paper’s pretrained model" I'm able to open the test_data.hdf5 file; however I can't seem to find those scores.

```
>>> res = h5py.File('test_data.hdf5')
>>> res.keys()
<KeysViewHDF5 ['epoch_0000']>
>>> res['epoch_0000'].keys()
<KeysViewHDF5 ['test']>
>>> res['epoch_0000']['test'].keys()
<KeysViewHDF5 ['mol', 'outputs', 'raw_outputs', 'targets']>

```
Where do those predicted docking scores wind up?

**Comment by manonreau** [comment]
Hi Erike, 

To read the content of the output file you can use the hdf5_to_csv script as you mentioned in the previous message to obtain a human readable csv file:
`python hdf5_to_csv.py [path to the hdf5 file]`

You can also chose to navigate through the hdf5 file. 

Here is the detail of the hdf5 content: 
- `mol` is the name of the system (i.e. initial pdb complex)
- `raw_outputs` contains the output of the model: if you are using a classification model, it will give you the probability to belong to each class
- `output` contains the transformed output of the model: if you are using a classification model, this will give you the predicted class for the current `mol`
- `targets` is the target value (ground truth that is provided as a reference in this example)

To access to those predictions you can use:
```
>>> res = h5py.File('test_data.hdf5')
>>> res.keys()
<KeysViewHDF5 ['epoch_0000']>
>>> res['epoch_0000'].keys()
<KeysViewHDF5 ['test']>
>>> res['epoch_0000/test'].keys()
<KeysViewHDF5 ['mol', 'outputs', 'raw_outputs', 'targets']>
>>> res['epoch_0000/test/outputs'][()]
```
Which is the equivalent of:
```
>>> res['epoch_0000']['test']['outputs'][()]
>>> res['epoch_0000/test'][outputs'][()]
```

Please let me know if you have other questions,

Manon

**Comment by erikedlund** [comment]
The problem I'm having is that the hdf5_to_csv script isn't working on any outputs I generate or the example files:

```
$:~/git/Deeprank-GNN$ ls -lha tests/hdf5/1ATN_residue.hdf5
-rw-rw-r-- 1 dnas dnas 811K May 12 16:22 tests/hdf5/1ATN_residue.hdf5
$:~/git/Deeprank-GNN$ python deeprank_gnn/tools/hdf5_to_csv.py tests/hdf5/1ATN_residue.hdf5
Please make sure that your input file if a HDF5 file
```

If I want to access those predictions directly from the file how can I do that? It's not clear from the contents of the 'outputs' object:

```
>>> vars(res['epoch_0000']['test']['outputs'])
{'_id': <h5py.h5d.DatasetID object at 0x7fb4024b4db0>, '_dcpl': <h5py.h5p.PropDCID object at 0x7fb40371c3b0>, '_dxpl': <h5py.h5p.PropDXID object at 0x7fb40371cc20>, '_filters': {}, '_readonly': True, '_cache_props': {}, '_local': <_thread._local object at 0x7fb4024b4d60>}
```

**Comment by manonreau** [comment]
Could you try to open the output of the model with this script and not the input graphs: 

`python deeprank_gnn/tools/hdf5_to_csv.py test_data.hdf5`

I am surprised to see the output of your `>>> vars(res['epoch_0000']['test']['outputs'])` command, could you please send me your test_data.hdf5 (manon.reau@gmail.com)

**Comment by erikedlund** [comment]
I get the same error for the generated model files:

```
$:~/git/Deeprank-GNN$ python deeprank_gnn/tools/hdf5_to_csv.py example/test_data.hdf5
Please make sure that your input file if a HDF5 file
```

Sure, I will send the files.

**Comment by manonreau** [comment]
The script indeed contained an error, you can get the updated one 
[here](https://github.com/DeepRank/Deeprank-GNN/blob/master/deeprank_gnn/tools/hdf5_to_csv.py) and try again the following command: 
`python hdf5_to_csv.py test_data.hdf5`

Please note that the command I mentioned above (`res['epoch_0000/test/outputs'][()]`) perfectly works on the output files:
```
>>> import h5py
>>> F=h5py.File('test_data.hdf5')
>>> F.keys()
<KeysViewHDF5 ['epoch_0000']>
>>> F['epoch_0000']
<HDF5 group "/epoch_0000" (1 members)>
>>> F['epoch_0000'].keys()
<KeysViewHDF5 ['test']>
>>> F['epoch_0000/test'].keys()
<KeysViewHDF5 ['mol', 'outputs', 'raw_outputs', 'targets']>
>>> F['epoch_0000/test/outputs'][()]
>>> F['epoch_0000/test/outputs'][()]
array([-0.05277156,  1.66766787,  1.56015444, -1.24365985, -0.0578917 ,
        0.66428864,  1.335482  ,  1.37477469, -0.56168133, -0.47044051])
```

**Comment by erikedlund** [comment]
Excellent, I synced up and was able to run the csv conversion script. Thank you for your assistance! Looks I failed to enter your exact command above, I was trying to inspect the output object and missed your suggestion.


So these values are classification probabilities? Are negative values one class and positive another?

```
array([-0.05277156,  1.66766787,  1.56015444, -1.24365985, -0.0578917 ,
        0.66428864,  1.335482  ,  1.37477469, -0.56168133, -0.47044051])
```

**Comment by manonreau** [comment]
Awesome !

If you refer to the Deeprank-GNN pre-print (the paper is on his way), this model has been trained in a regression mode using the fraction of native contact as a target value. 
The goal was to assign a score to different docking models to rank them from the worst to the best (or vice versa).
The final score is thus continuous and should only be used to rank the models, the higher the score the better.
